### ISSUE TITLE
Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by flamedfury** [katydecorah/read-action#110]
**Describe the bug**

- Run workflow from actions
- Enter ISBN `9780987434739` for book that exists on Google Books (https://www.google.co.nz/books/edition/The_Mothership/SGZsnQEACAAJ?hl=en)
- The action runs and fails.

**To Reproduce**
1. Go to https://github.com/flamedfury/metadata-library/actions/runs/3983544077/jobs/6828982134
2. Click on `Read`
4. See error ` Error: Cannot read properties of undefined (reading 'startsWith')`

**Expected behavior**

I expected to the action to complete successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/4757066/213974030-42b9c98e-86fe-49f6-a6ed-2f28f4a70c58.png)

**Desktop (please complete the following information):**
 - OS: [Pop!_OS 22.04 LTS]
 - Browser [Firefox]
 - Version [108.0.2 (64-bit)]
 
**Additional context**

This has happened with number of books, I have worked around by clicking on a different edition and running the action again with a different ISBN. 

For this book, this is the only edition, so am unable to enter a new ISBN.

**Comment by katydecorah** [comment]
Thanks so much for this issue! Looks like the action was acting too strict on expecting some properties that some books may no have. Fix incoming!
