### ISSUE TITLE
Add support for larger versions of book cover images

### ISSUE THREAD

**Issue by flamedfury** [katydecorah/read-action#133]
**Is your feature request related to a problem? Please describe.**
The cover image thumbnails are too small for how my website displays images.

**Describe the solution you'd like**
I would like a new option in the workflow/action that can be enabled to download a high res version of the book cover. This way, I can use a plugin when generating my website to create different-sized versions of the cover to use as needed.

**Describe alternatives you've considered**
I'm considering curating my versions of the book covers and committing them to my repo. (I'm still not a fan of the media available in Google Books anyway :P )

**Additional context**
n/a

**Comment by katydecorah** [comment]
Thanks for your patience! I think I found a way to make this happen in #134!

**Comment by flamedfury** [comment]
This is working great so far. I am going through and re-adding all my books :D
