### ISSUE TITLE
Store downloaded image in read.json

### ISSUE THREAD

**Issue by flamedfury** [katydecorah/read-action#154]
**Is your feature request related to a problem? Please describe.**
I'm trying to use [eleventy-img](https://github.com/11ty/eleventy-img/issues) to optimise the downloaded book covers on my bookshelf page. 

I'm currently displaying the book covers without optimisation with a simple `<img>` tag with `https://raw.githubusercontent.com/flamedfury/metadata-library/main/img/book-{{ book.isbn }}.png` as the URL structure.

I cannot use this URL structure with eleventy-image; I can use it with something like `{{ book.image }}`.

The `thumbnail` URL is also not able to be used `"thumbnail": "https://books.google.com/books/content?id=NCSYZ41UBaYC&printsec=frontcover&img=1&zoom=1&source=gbs_api&w=1280",`.

**Describe the solution you'd like**
I would like URL to the downloaded bookcover, e.g. `` to be injected into the JSON file so I can render it with a simple Nunjuck tag `{{ book.image }}`. 

**Additional context**
I have no idea whether this is possible

**Comment by katydecorah** [comment]
Thanks for your patience! Looking at the nunjucks docs, I see the implementation to be:

```
{% image "cat.jpg", "photo of my tabby cat" %}
```

Is the idea that you want to do? (Or whatever the syntax is for using a template var...)

```
{% image book.image, "photo of my tabby cat" %}
```

One short term solution might be to concatenate the strings as I've done this myself with liquid! I found this blog post for nunjucks: https://michaelheap.com/nunjucks-concatenate-string/

I can look into the long term solution, but it will take a small refactor on my end.

**Comment by katydecorah** [comment]
This will be in the next version! I put this behind a flag, please update your workflow to enable it, like this:


```yaml
with:
  set-image: true
```

**Comment by flamedfury** [comment]
thank you @katydecorah I will dive into this over the weekend 😃
